### ISSUE TITLE
カバーいりませんか

### ISSUE THREAD

**Issue by spicagraph** [torounit/responsive-slide#2]
![responsive-slide-128-128](https://cloud.githubusercontent.com/assets/3328899/22852582/fa3fe652-f081-11e6-8b15-76b21157283d.png)
![responsive-slide-256-256](https://cloud.githubusercontent.com/assets/3328899/22852581/fa3f41d4-f081-11e6-962b-1922775e277c.png)
![responsive-slide-1544-500](https://cloud.githubusercontent.com/assets/3328899/22852583/fa41edee-f081-11e6-8750-e591b7a08518.png)

**Comment by torounit** [comment]
@spicagraph Thanks!! https://wordpress.org/plugins/responsive-slide/
